python_distribution(
    dependencies=[
        "./hcl2_type_reflection",
    ],
    provides=setup_py(
        name="hcl2-type-reflection",
        version="0.0.1",
        readme="README.md",
        description="Lib to get the types from HCL2 input variables",
    ),
)
