grapl_python_distribution(
    dependencies=[
        "./grapl_common",
        "./grapl_common:py_typed",
    ],
    provides=setup_py(
        name="grapl-common",
        version="0.0.6",  # TODO: remove VERSION file? Or read from it?
        description="Shared code between Grapl components",
    ),
)
