#!/usr/bin/env bash

set -euo pipefail

# Generate / update a constraints file for Pants to use when
# installing 3rd party Python dependencies.
#
# Operates by querying Pants itself to gather all the dependencies
# declared throughout the Python code, installing them into a
# transient virtualenv, and then outputting the resolved dependencies
# to a file for Pants to use.
#
# Should be run each time new dependencies are added, or periodically
# as desired to update dependencies.
#
# This script is borrowed from the Pants documentation itself:
# https://www.pantsbuild.org/docs/python-third-party-dependencies

# NOTE: This script implicitly assumes it is being run from the
# top-level of the repository!

python=python3
# This directory should be .gitignored, and should only be used by
# this script.
VIRTUALENV=build-support/.constraints-venv
pip="${VIRTUALENV}/bin/pip"
requirements_file=3rdparty/python/requirements.txt
constraints_file=3rdparty/python/constraints.txt

# Remove any existing virutalenv, to ensure we're running with a
# "clean slate".
#
# We could also handle this at the end with a signal trap, but that
# would remove the ability to inspect the virtualenv after the fact.
rm -Rf "${VIRTUALENV}"

"${python}" -m venv "${VIRTUALENV}"
"${pip}" install pip --upgrade

# Install all our requirements.txt, and also any 3rdparty
# dependencies specified outside requirements.txt, e.g. via a
# handwritten python_requirement_library target.
"${pip}" install \
  --requirement "${requirements_file}" \
  --requirement <(./pants dependencies --type=3rdparty ::)

cat <<EOF > "${constraints_file}"
# Generated by build-support/generate_constraints.sh on $(date)
# DO NOT EDIT BY HAND
EOF

# Apparently `pip freeze` erroneously inserts `pkg-resources==0.0.0`
# on Ubuntu / Debian, which tends to breaks things. So we'll just
# filter that out.
#
# https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command
"${pip}" freeze --all | \
    grep -v "pkg-resources==0.0.0" \
         >> "${constraints_file}"
