# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ip_asset_mapping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ip_asset_mapping.proto',
  package='ip_asset_mapping',
  syntax='proto3',
  serialized_pb=_b('\n\x1cproto/ip_asset_mapping.proto\x12\x10ip_asset_mapping\"A\n\x0eIpAssetMapping\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\"E\n\x0fIpAssetMappings\x12\x32\n\x08mappings\x18\x01 \x03(\x0b\x32 .ip_asset_mapping.IpAssetMappingb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IPASSETMAPPING = _descriptor.Descriptor(
  name='IpAssetMapping',
  full_name='ip_asset_mapping.IpAssetMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ip_asset_mapping.IpAssetMapping.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='ip_asset_mapping.IpAssetMapping.asset_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ip_asset_mapping.IpAssetMapping.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=115,
)


_IPASSETMAPPINGS = _descriptor.Descriptor(
  name='IpAssetMappings',
  full_name='ip_asset_mapping.IpAssetMappings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mappings', full_name='ip_asset_mapping.IpAssetMappings.mappings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=186,
)

_IPASSETMAPPINGS.fields_by_name['mappings'].message_type = _IPASSETMAPPING
DESCRIPTOR.message_types_by_name['IpAssetMapping'] = _IPASSETMAPPING
DESCRIPTOR.message_types_by_name['IpAssetMappings'] = _IPASSETMAPPINGS

IpAssetMapping = _reflection.GeneratedProtocolMessageType('IpAssetMapping', (_message.Message,), dict(
  DESCRIPTOR = _IPASSETMAPPING,
  __module__ = 'proto.ip_asset_mapping_pb2'
  # @@protoc_insertion_point(class_scope:ip_asset_mapping.IpAssetMapping)
  ))
_sym_db.RegisterMessage(IpAssetMapping)

IpAssetMappings = _reflection.GeneratedProtocolMessageType('IpAssetMappings', (_message.Message,), dict(
  DESCRIPTOR = _IPASSETMAPPINGS,
  __module__ = 'proto.ip_asset_mapping_pb2'
  # @@protoc_insertion_point(class_scope:ip_asset_mapping.IpAssetMappings)
  ))
_sym_db.RegisterMessage(IpAssetMappings)


# @@protoc_insertion_point(module_scope)
