# syntax=docker/dockerfile:1.3-labs

FROM debian:bullseye-slim AS rootfs-build

RUN --mount=type=cache,target=/var/lib/apt/lists,sharing=locked,id=rootfs-apt <<EOF
    apt update
    apt install --yes \
        fuse\
        fuseext2
EOF

COPY docker_runtime docker_runtime

ENTRYPOINT [ "./docker_runtime/create_rootfs_image.sh" ]