grapl_python_distribution(
    dependencies=[
        "./grapl_analyzerlib",
        "./grapl_analyzerlib:py_typed",
        "./grapl_analyzerlib/nodes",
    ],
    provides=setup_py(
        name="grapl-analyzerlib",
        version="0.2.73",  # TODO: remove VERSION file? Or read from it?
        description="Library for Grapl Analyzers",
    ),
)
