/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CsiControllerInfo {
    #[serde(
        rename = "SupportsAttachDetach",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_attach_detach: Option<bool>,
    #[serde(
        rename = "SupportsListVolumes",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_list_volumes: Option<bool>,
    #[serde(
        rename = "SupportsListVolumesAttachedNodes",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_list_volumes_attached_nodes: Option<bool>,
    #[serde(
        rename = "SupportsReadOnlyAttach",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_read_only_attach: Option<bool>,
}

impl CsiControllerInfo {
    pub fn new() -> CsiControllerInfo {
        CsiControllerInfo {
            supports_attach_detach: None,
            supports_list_volumes: None,
            supports_list_volumes_attached_nodes: None,
            supports_read_only_attach: None,
        }
    }
}
