grapl_python_distribution(
    dependencies = [
        "./python_proto",
    ],
    provides = setup_py(
        name = "python_proto",
        version = "0.0.1",
        readme = "README.md",
        description = "protobuf serde library for grapl's python services",
    ),
)
