//
// asset_id: impl Into<Option<String>>,
// hostname: impl Into<Option<String>>,
// state: FileState,
// timestamp: u64,
// file_name: String,
// file_path: String,
// file_extension: String,
// file_mime_type: String,
// file_size: u64,
// file_version: String,
// file_description: String,
// file_product: String,
// file_company: String,
// file_directory: String,
// file_inode: u64,
// file_hard_links: u64,
// md5_hash: String,
// sha1_hash: String,
// sha256_hash: String,
