//
// src_ip_address: impl Into<String>,
// dst_ip_address: impl Into<String>,
// protocol: impl Into<String>,
// src_port: u16,
// dst_port: u16,
// state: NetworkConnectionState,
// created_timestamp: u64,
// terminated_timestamp: u64,
// last_seen_timestamp: u64,
