//
// asset_id: impl Into<Option<String>>,
// hostname: impl Into<Option<String>>,
// state: ProcessInboundConnectionState,
// port: u16,
// ip_address: impl Into<String>,
// protocol: impl Into<String>,
// created_timestamp: u64,
// terminated_timestamp: u64,
// last_seen_timestamp: u64,
