protobuf_library(
    name="graplinc",
    # Since we distribute generated code for Python at this level, it
    # makes sense to also collect the sources for all subdirectories
    # at this level, rather than specifying BUILD files in each
    # subdirectory.
    sources=["graplinc/**/*.proto"],
)
