grapl_python_distribution(
    dependencies=[
        "./grapl_tests_common",
        "./grapl_tests_common:py_typed",
        "./grapl_tests_common/clients",
    ],
    provides=setup_py(
        name="grapl-tests-common",
        version="0.0.6",
        description="Shared code between Grapl end-to-end tests",
    ),
)
