python_library(
    name="repl",
    dependencies=[
        'src/python/grapl-common',
        'src/python/grapl-tests-common',
        # ^ Don't be afraid to add more dependencies here as-needed!
    ],
    sources=[],
)