python_tests()

python_sources(name="tests_lib")

# get format checks on the test
# test is run manually from CI, not by Pants
shell_sources(
    name="shell_lib",
    sources=["integration_test.sh"],
)
