/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use std::option::Option;
use std::{
    borrow::Borrow,
    pin::Pin,
    rc::Rc,
};

use futures::Future;
use hyper;

use super::{
    configuration,
    request as __internal_request,
    Error,
};

pub struct DeploymentsApiClient<C: hyper::client::connect::Connect>
where
    C: Clone + std::marker::Send + Sync + 'static,
{
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::connect::Connect> DeploymentsApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> DeploymentsApiClient<C> {
        DeploymentsApiClient { configuration }
    }
}

pub trait DeploymentsApi {
    fn get_deployment(
        &self,
        deployment_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::Deployment, Error>>>>;
    fn get_deployment_allocations(
        &self,
        deployment_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<crate::models::AllocationListStub>, Error>>>>;
    fn get_deployments(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<crate::models::Deployment>, Error>>>>;
    fn post_deployment_allocation_health(
        &self,
        deployment_id: &str,
        deployment_alloc_health_request: crate::models::DeploymentAllocHealthRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>>;
    fn post_deployment_fail(
        &self,
        deployment_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>>;
    fn post_deployment_pause(
        &self,
        deployment_id: &str,
        deployment_pause_request: crate::models::DeploymentPauseRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>>;
    fn post_deployment_promote(
        &self,
        deployment_id: &str,
        deployment_promote_request: crate::models::DeploymentPromoteRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>>;
    fn post_deployment_unblock(
        &self,
        deployment_id: &str,
        deployment_unblock_request: crate::models::DeploymentUnblockRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>>;
}

impl<C: hyper::client::connect::Connect> DeploymentsApi for DeploymentsApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    #[allow(unused_mut)]
    fn get_deployment(
        &self,
        deployment_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::Deployment, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/deployment/{deploymentID}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = wait {
            let query_value = s.to_string();
            req = req.with_query_param("wait".to_string(), query_value);
        }
        if let Some(ref s) = stale {
            let query_value = s.to_string();
            req = req.with_query_param("stale".to_string(), query_value);
        }
        if let Some(ref s) = prefix {
            let query_value = s.to_string();
            req = req.with_query_param("prefix".to_string(), query_value);
        }
        if let Some(ref s) = per_page {
            let query_value = s.to_string();
            req = req.with_query_param("per_page".to_string(), query_value);
        }
        if let Some(ref s) = next_token {
            let query_value = s.to_string();
            req = req.with_query_param("next_token".to_string(), query_value);
        }
        req = req.with_path_param("deploymentID".to_string(), deployment_id.to_string());
        if let Some(param_value) = index {
            req = req.with_header_param("index".to_string(), param_value.to_string());
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_deployment_allocations(
        &self,
        deployment_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<crate::models::AllocationListStub>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/deployment/allocations/{deploymentID}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = wait {
            let query_value = s.to_string();
            req = req.with_query_param("wait".to_string(), query_value);
        }
        if let Some(ref s) = stale {
            let query_value = s.to_string();
            req = req.with_query_param("stale".to_string(), query_value);
        }
        if let Some(ref s) = prefix {
            let query_value = s.to_string();
            req = req.with_query_param("prefix".to_string(), query_value);
        }
        if let Some(ref s) = per_page {
            let query_value = s.to_string();
            req = req.with_query_param("per_page".to_string(), query_value);
        }
        if let Some(ref s) = next_token {
            let query_value = s.to_string();
            req = req.with_query_param("next_token".to_string(), query_value);
        }
        req = req.with_path_param("deploymentID".to_string(), deployment_id.to_string());
        if let Some(param_value) = index {
            req = req.with_header_param("index".to_string(), param_value.to_string());
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_deployments(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<crate::models::Deployment>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/deployments".to_string())
                .with_auth(__internal_request::Auth::ApiKey(
                    __internal_request::ApiKey {
                        in_header: true,
                        in_query: false,
                        param_name: "X-Nomad-Token".to_owned(),
                    },
                ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = wait {
            let query_value = s.to_string();
            req = req.with_query_param("wait".to_string(), query_value);
        }
        if let Some(ref s) = stale {
            let query_value = s.to_string();
            req = req.with_query_param("stale".to_string(), query_value);
        }
        if let Some(ref s) = prefix {
            let query_value = s.to_string();
            req = req.with_query_param("prefix".to_string(), query_value);
        }
        if let Some(ref s) = per_page {
            let query_value = s.to_string();
            req = req.with_query_param("per_page".to_string(), query_value);
        }
        if let Some(ref s) = next_token {
            let query_value = s.to_string();
            req = req.with_query_param("next_token".to_string(), query_value);
        }
        if let Some(param_value) = index {
            req = req.with_header_param("index".to_string(), param_value.to_string());
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_deployment_allocation_health(
        &self,
        deployment_id: &str,
        deployment_alloc_health_request: crate::models::DeploymentAllocHealthRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/deployment/allocation-health/{deploymentID}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        req = req.with_path_param("deploymentID".to_string(), deployment_id.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(deployment_alloc_health_request);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_deployment_fail(
        &self,
        deployment_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/deployment/fail/{deploymentID}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        req = req.with_path_param("deploymentID".to_string(), deployment_id.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_deployment_pause(
        &self,
        deployment_id: &str,
        deployment_pause_request: crate::models::DeploymentPauseRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/deployment/pause/{deploymentID}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        req = req.with_path_param("deploymentID".to_string(), deployment_id.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(deployment_pause_request);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_deployment_promote(
        &self,
        deployment_id: &str,
        deployment_promote_request: crate::models::DeploymentPromoteRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/deployment/promote/{deploymentID}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        req = req.with_path_param("deploymentID".to_string(), deployment_id.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(deployment_promote_request);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_deployment_unblock(
        &self,
        deployment_id: &str,
        deployment_unblock_request: crate::models::DeploymentUnblockRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::DeploymentUpdateResponse, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/deployment/unblock/{deploymentID}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        req = req.with_path_param("deploymentID".to_string(), deployment_id.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(deployment_unblock_request);

        req.execute(self.configuration.borrow())
    }
}
