/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use std::option::Option;
use std::{
    borrow::Borrow,
    pin::Pin,
    rc::Rc,
};

use futures::Future;
use hyper;

use super::{
    configuration,
    request as __internal_request,
    Error,
};

pub struct VolumesApiClient<C: hyper::client::connect::Connect>
where
    C: Clone + std::marker::Send + Sync + 'static,
{
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::connect::Connect> VolumesApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> VolumesApiClient<C> {
        VolumesApiClient { configuration }
    }
}

pub trait VolumesApi {
    fn create_volume(
        &self,
        volume_id: &str,
        action: &str,
        csi_volume_create_request: crate::models::CsiVolumeCreateRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>>;
    fn delete_snapshot(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
        plugin_id: Option<&str>,
        snapshot_id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>>;
    fn delete_volume_registration(
        &self,
        volume_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
        force: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>>;
    fn detach_or_delete_volume(
        &self,
        volume_id: &str,
        action: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
        node: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>>;
    fn get_external_volumes(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
        plugin_id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiVolumeListExternalResponse, Error>>>>;
    fn get_snapshots(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
        plugin_id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiSnapshotListResponse, Error>>>>;
    fn get_volume(
        &self,
        volume_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiVolume, Error>>>>;
    fn get_volumes(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
        node_id: Option<&str>,
        plugin_id: Option<&str>,
        _type: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<crate::models::CsiVolumeListStub>, Error>>>>;
    fn post_snapshot(
        &self,
        csi_snapshot_create_request: crate::models::CsiSnapshotCreateRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiSnapshotCreateResponse, Error>>>>;
    fn post_volume(
        &self,
        csi_volume_register_request: crate::models::CsiVolumeRegisterRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>>;
    fn post_volume_registration(
        &self,
        volume_id: &str,
        csi_volume_register_request: crate::models::CsiVolumeRegisterRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>>;
}

impl<C: hyper::client::connect::Connect> VolumesApi for VolumesApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    #[allow(unused_mut)]
    fn create_volume(
        &self,
        volume_id: &str,
        action: &str,
        csi_volume_create_request: crate::models::CsiVolumeCreateRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/volume/csi/{volumeId}/{action}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        req = req.with_path_param("volumeId".to_string(), volume_id.to_string());
        req = req.with_path_param("action".to_string(), action.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(csi_volume_create_request);
        req = req.returns_nothing();

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_snapshot(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
        plugin_id: Option<&str>,
        snapshot_id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/volumes/snapshot".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        if let Some(ref s) = plugin_id {
            let query_value = s.to_string();
            req = req.with_query_param("plugin_id".to_string(), query_value);
        }
        if let Some(ref s) = snapshot_id {
            let query_value = s.to_string();
            req = req.with_query_param("snapshot_id".to_string(), query_value);
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.returns_nothing();

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_volume_registration(
        &self,
        volume_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
        force: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/volume/csi/{volumeId}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        if let Some(ref s) = force {
            let query_value = s.to_string();
            req = req.with_query_param("force".to_string(), query_value);
        }
        req = req.with_path_param("volumeId".to_string(), volume_id.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.returns_nothing();

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn detach_or_delete_volume(
        &self,
        volume_id: &str,
        action: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
        node: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/volume/csi/{volumeId}/{action}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        if let Some(ref s) = node {
            let query_value = s.to_string();
            req = req.with_query_param("node".to_string(), query_value);
        }
        req = req.with_path_param("volumeId".to_string(), volume_id.to_string());
        req = req.with_path_param("action".to_string(), action.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.returns_nothing();

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_external_volumes(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
        plugin_id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiVolumeListExternalResponse, Error>>>>
    {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/volumes/external".to_string())
                .with_auth(__internal_request::Auth::ApiKey(
                    __internal_request::ApiKey {
                        in_header: true,
                        in_query: false,
                        param_name: "X-Nomad-Token".to_owned(),
                    },
                ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = wait {
            let query_value = s.to_string();
            req = req.with_query_param("wait".to_string(), query_value);
        }
        if let Some(ref s) = stale {
            let query_value = s.to_string();
            req = req.with_query_param("stale".to_string(), query_value);
        }
        if let Some(ref s) = prefix {
            let query_value = s.to_string();
            req = req.with_query_param("prefix".to_string(), query_value);
        }
        if let Some(ref s) = per_page {
            let query_value = s.to_string();
            req = req.with_query_param("per_page".to_string(), query_value);
        }
        if let Some(ref s) = next_token {
            let query_value = s.to_string();
            req = req.with_query_param("next_token".to_string(), query_value);
        }
        if let Some(ref s) = plugin_id {
            let query_value = s.to_string();
            req = req.with_query_param("plugin_id".to_string(), query_value);
        }
        if let Some(param_value) = index {
            req = req.with_header_param("index".to_string(), param_value.to_string());
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_snapshots(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
        plugin_id: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiSnapshotListResponse, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/volumes/snapshot".to_string())
                .with_auth(__internal_request::Auth::ApiKey(
                    __internal_request::ApiKey {
                        in_header: true,
                        in_query: false,
                        param_name: "X-Nomad-Token".to_owned(),
                    },
                ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = wait {
            let query_value = s.to_string();
            req = req.with_query_param("wait".to_string(), query_value);
        }
        if let Some(ref s) = stale {
            let query_value = s.to_string();
            req = req.with_query_param("stale".to_string(), query_value);
        }
        if let Some(ref s) = prefix {
            let query_value = s.to_string();
            req = req.with_query_param("prefix".to_string(), query_value);
        }
        if let Some(ref s) = per_page {
            let query_value = s.to_string();
            req = req.with_query_param("per_page".to_string(), query_value);
        }
        if let Some(ref s) = next_token {
            let query_value = s.to_string();
            req = req.with_query_param("next_token".to_string(), query_value);
        }
        if let Some(ref s) = plugin_id {
            let query_value = s.to_string();
            req = req.with_query_param("plugin_id".to_string(), query_value);
        }
        if let Some(param_value) = index {
            req = req.with_header_param("index".to_string(), param_value.to_string());
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_volume(
        &self,
        volume_id: &str,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiVolume, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/volume/csi/{volumeId}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = wait {
            let query_value = s.to_string();
            req = req.with_query_param("wait".to_string(), query_value);
        }
        if let Some(ref s) = stale {
            let query_value = s.to_string();
            req = req.with_query_param("stale".to_string(), query_value);
        }
        if let Some(ref s) = prefix {
            let query_value = s.to_string();
            req = req.with_query_param("prefix".to_string(), query_value);
        }
        if let Some(ref s) = per_page {
            let query_value = s.to_string();
            req = req.with_query_param("per_page".to_string(), query_value);
        }
        if let Some(ref s) = next_token {
            let query_value = s.to_string();
            req = req.with_query_param("next_token".to_string(), query_value);
        }
        req = req.with_path_param("volumeId".to_string(), volume_id.to_string());
        if let Some(param_value) = index {
            req = req.with_header_param("index".to_string(), param_value.to_string());
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_volumes(
        &self,
        region: Option<&str>,
        namespace: Option<&str>,
        index: Option<i32>,
        wait: Option<&str>,
        stale: Option<&str>,
        prefix: Option<&str>,
        x_nomad_token: Option<&str>,
        per_page: Option<i32>,
        next_token: Option<&str>,
        node_id: Option<&str>,
        plugin_id: Option<&str>,
        _type: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<crate::models::CsiVolumeListStub>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/volumes".to_string())
            .with_auth(__internal_request::Auth::ApiKey(
                __internal_request::ApiKey {
                    in_header: true,
                    in_query: false,
                    param_name: "X-Nomad-Token".to_owned(),
                },
            ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = wait {
            let query_value = s.to_string();
            req = req.with_query_param("wait".to_string(), query_value);
        }
        if let Some(ref s) = stale {
            let query_value = s.to_string();
            req = req.with_query_param("stale".to_string(), query_value);
        }
        if let Some(ref s) = prefix {
            let query_value = s.to_string();
            req = req.with_query_param("prefix".to_string(), query_value);
        }
        if let Some(ref s) = per_page {
            let query_value = s.to_string();
            req = req.with_query_param("per_page".to_string(), query_value);
        }
        if let Some(ref s) = next_token {
            let query_value = s.to_string();
            req = req.with_query_param("next_token".to_string(), query_value);
        }
        if let Some(ref s) = node_id {
            let query_value = s.to_string();
            req = req.with_query_param("node_id".to_string(), query_value);
        }
        if let Some(ref s) = plugin_id {
            let query_value = s.to_string();
            req = req.with_query_param("plugin_id".to_string(), query_value);
        }
        if let Some(ref s) = _type {
            let query_value = s.to_string();
            req = req.with_query_param("type".to_string(), query_value);
        }
        if let Some(param_value) = index {
            req = req.with_header_param("index".to_string(), param_value.to_string());
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_snapshot(
        &self,
        csi_snapshot_create_request: crate::models::CsiSnapshotCreateRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::CsiSnapshotCreateResponse, Error>>>>
    {
        let mut req =
            __internal_request::Request::new(hyper::Method::POST, "/volumes/snapshot".to_string())
                .with_auth(__internal_request::Auth::ApiKey(
                    __internal_request::ApiKey {
                        in_header: true,
                        in_query: false,
                        param_name: "X-Nomad-Token".to_owned(),
                    },
                ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(csi_snapshot_create_request);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_volume(
        &self,
        csi_volume_register_request: crate::models::CsiVolumeRegisterRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::POST, "/volumes".to_string())
            .with_auth(__internal_request::Auth::ApiKey(
                __internal_request::ApiKey {
                    in_header: true,
                    in_query: false,
                    param_name: "X-Nomad-Token".to_owned(),
                },
            ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(csi_volume_register_request);
        req = req.returns_nothing();

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn post_volume_registration(
        &self,
        volume_id: &str,
        csi_volume_register_request: crate::models::CsiVolumeRegisterRequest,
        region: Option<&str>,
        namespace: Option<&str>,
        x_nomad_token: Option<&str>,
        idempotency_token: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = Result<(), Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/volume/csi/{volumeId}".to_string(),
        )
        .with_auth(__internal_request::Auth::ApiKey(
            __internal_request::ApiKey {
                in_header: true,
                in_query: false,
                param_name: "X-Nomad-Token".to_owned(),
            },
        ));
        if let Some(ref s) = region {
            let query_value = s.to_string();
            req = req.with_query_param("region".to_string(), query_value);
        }
        if let Some(ref s) = namespace {
            let query_value = s.to_string();
            req = req.with_query_param("namespace".to_string(), query_value);
        }
        if let Some(ref s) = idempotency_token {
            let query_value = s.to_string();
            req = req.with_query_param("idempotency_token".to_string(), query_value);
        }
        req = req.with_path_param("volumeId".to_string(), volume_id.to_string());
        if let Some(param_value) = x_nomad_token {
            req = req.with_header_param("X-Nomad-Token".to_string(), param_value.to_string());
        }
        req = req.with_body_param(csi_volume_register_request);
        req = req.returns_nothing();

        req.execute(self.configuration.borrow())
    }
}
