#!/bin/bash
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

set -eu

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
GRAPL_REPO_ROOT=$(realpath "$THIS_DIR/../..")

$GRAPL_REPO_ROOT/etc/ci_scripts/py_lint.sh