FROM ubuntu

# Feel free to add whatever convenient testing utilities you like.
RUN apt-get update && apt-get install --yes \
    curl \
    htop \
    iputils-ping \
    jq \
    net-tools \
    nmap \
    strace \
    wget
